;*****************************************************************
;
;	Light Speed Player v1.26
;	Fastest Amiga MOD player ever :)
;	Written By Arnaud Carré (aka Leonard / OXYGENE)
;	https://github.com/arnaud-carre/LSPlayer
;	twitter: @leonard_coder
;
;	"Insane speed" player version ( half scanline average player time! )
;	(this source code is generated by LSPConvert)
;	You can also use the generic LightSpeedPlayer.asm player ( less than 512bytes! )
;
;	*WARNING* This generated source code specific to "stuck-in-the-middle.lsmusic" LSP file
;
;	--------How to use--------- 
;
;	bsr LSP_MusicInitInsane : Init LSP player code & music
;		a0: LSP music data(any memory)
;		a1: LSP sound bank(chip memory)
;		a2: DMACON 8bits low byte address (odd)
;
;	bsr LSP_MusicPlayTickInsane : LSP player tick (call once per frame)
;		a6: should be $dff0a0 (and not $dff000)
;		Used regs: d0/a0/a1/a2/a3/a4
;
;*****************************************************************

LSP_MusicInitInsane:
			move.l	#$6f9016f6,d0
			cmp.l	(a1),d0
			bne.s	.dataError
			cmpi.l	#'LSP1',(a0)+
			bne.s	.dataError
			cmp.l	(a0)+,d0
			bne.s	.dataError
			lea		2(a0),a5		; relocation byte
			lea		878(a0),a0		; skip header
			lea		LSP_StateInsane(pc),a3
			move.l	a2,12(a3)
			move.l	a0,16(a3)		; word stream ptr
			lea		6490(a0),a4
			move.l	a4,8(a3)		; byte stream ptr

			lea		252(a0),a0	; word stream loop pos
			move.l	a0,(a3)	; word stream loop ptr
			lea		516(a4),a4	; byte stream loop pos
			move.l	a4,24(a3)	; byte stream loop ptr
			tst.b	(a5)
			bne.s	.noReloc
			st		(a5)
			moveq	#27-1,d0
			lea		LSP_InstrumentInfoInsane(pc),a0
			move.l	a1,d1
.rloop:		add.l	d1,(a0)
			add.l	d1,6(a0)
			lea		12(a0),a0
			dbf		d0,.rloop
.noReloc:	bset.b	#1,$bfe001	; disable this fucking Low pass filter!!
			lea		LSP_StateInsane+6(pc),a0
			move.w	#125,(a0)		; music BPM
			rts

.dataError:	illegal

LSP_MusicGetPos:
			moveq	#0,d0		; (music have been generated without "-getpos" support)
			rts

LSP_StateInsane:	dc.l	0			; 0  word stream loop
					dc.w	0			; 4  reloc has been done
					dc.w	0			; 6  current music BPM
					dc.l	0			; 8  byte stream
					dc.l	0			; 12 m_lfmDmaConPatch
					dc.l	0			; 16 word stream
					dc.l	0			; 20 word stream loop
					dc.l	0			; 24 byte stream loop

; WARNING: in word stream, instrument offset is shifted by -12 bytes (3 last long of LSP_StateInsane)
LSP_InstrumentInfoInsane:			; (27 instruments)
			dc.w	$0000,$3468,$05cd,$0000,$3468,$0001
			dc.w	$0000,$4002,$0654,$0000,$4666,$0322
			dc.w	$0000,$9766,$16ed,$0000,$9766,$0001
			dc.w	$0000,$c540,$11b2,$0000,$c540,$0001
			dc.w	$0001,$b798,$1191,$0001,$c9a8,$0889
			dc.w	$0000,$0004,$085d,$0000,$0004,$0001
			dc.w	$0000,$e8a4,$07c1,$0000,$e8a4,$0001
			dc.w	$0000,$4caa,$17cf,$0000,$4caa,$0001
			dc.w	$0000,$8526,$0920,$0000,$8526,$0001
			dc.w	$0000,$f826,$09bd,$0000,$f826,$0001
			dc.w	$0000,$227a,$0479,$0000,$227a,$0001
			dc.w	$0001,$9056,$0912,$0001,$975e,$058e
			dc.w	$0001,$0ba0,$07cb,$0001,$0ba0,$0001
			dc.w	$0001,$1b36,$0ace,$0001,$1b36,$0001
			dc.w	$0001,$30d2,$09c9,$0001,$30d2,$0001
			dc.w	$0001,$4464,$0f8f,$0001,$4464,$0001
			dc.w	$0001,$5664,$068f,$0001,$4464,$0001
			dc.w	$0001,$6382,$166a,$0001,$6382,$0001
			dc.w	$0001,$7782,$0c6a,$0001,$6382,$0001
			dc.w	$0001,$a27a,$0a8f,$0001,$a27a,$0001
			dc.w	$0001,$daba,$0f9f,$0001,$daba,$0001
			dc.w	$0001,$f9f8,$07d0,$0001,$f9f8,$0001
			dc.w	$0002,$0998,$1d4a,$0002,$2c5c,$0be8
			dc.w	$0000,$2b6c,$047e,$0000,$2b6c,$0001
			dc.w	$0002,$442c,$1a70,$0002,$6774,$08cc
			dc.w	$0000,$10be,$08de,$0000,$10be,$0001
			dc.w	$0000,$7c48,$046f,$0000,$7c48,$0001

LSP_MusicPlayTickInsane:
			lea		LSP_StateInsane+8(pc),a1
			move.l	(a1),a0		; byte stream
.process:	moveq	#0,d0
			move.b	(a0)+,d0
			beq.s	.extended1
			add.w	d0,d0
			move.w	.LSP_JmpTable(pc,d0.w),d0	; 14 cycles
			jmp		.LSP_JmpTable(pc,d0.w)		; 14 cycles

.extended1:	move.w	#$0100,d0
			move.b	(a0)+,d0
			add.w	d0,d0
			move.w	.LSP_JmpTable(pc,d0.w),d0
			jmp		.LSP_JmpTable(pc,d0.w)

.r_rewind:	move.l	0-8(a1),16-8(a1)
			move.l	24-8(a1),a0
			bra.s	.process

.resetv:	dc.l	0,0,0,0

.LSP_JmpTable:		; (258 codes)
			dc.w	-1		; extended code
			dc.w	.r_None-.LSP_JmpTable
			dc.w	.r_Bp-.LSP_JmpTable
			dc.w	.r_Bv-.LSP_JmpTable
			dc.w	.r_ArBrCrDr-.LSP_JmpTable
			dc.w	.r_BvDv-.LSP_JmpTable
			dc.w	.r_Cp-.LSP_JmpTable
			dc.w	.r_ArCrDr-.LSP_JmpTable
			dc.w	.r_Ar-.LSP_JmpTable
			dc.w	.r_AtvpCtpDtv-.LSP_JmpTable
			dc.w	.r_ArBrDr-.LSP_JmpTable
			dc.w	.r_AtvCtpDtv-.LSP_JmpTable
			dc.w	.r_ArBrpCrDr-.LSP_JmpTable
			dc.w	.r_Br-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtpDtv-.LSP_JmpTable
			dc.w	.r_ArBvCrDr-.LSP_JmpTable
			dc.w	.r_AtvBtpCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtpDtv-.LSP_JmpTable
			dc.w	.r_Cr-.LSP_JmpTable
			dc.w	.r_Dv-.LSP_JmpTable
			dc.w	.r_BpCp-.LSP_JmpTable
			dc.w	.r_Cv-.LSP_JmpTable
			dc.w	.r_Ctp-.LSP_JmpTable
			dc.w	.r_AtvBtvCtpDtv-.LSP_JmpTable
			dc.w	.r_Atv-.LSP_JmpTable
			dc.w	.r_ArDr-.LSP_JmpTable
			dc.w	.r_Btp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtpDtv-.LSP_JmpTable
			dc.w	.r_Atvp-.LSP_JmpTable
			dc.w	.r_Btv-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtvDtv-.LSP_JmpTable
			dc.w	.r_ArBrCr-.LSP_JmpTable
			dc.w	.r_CpDv-.LSP_JmpTable
			dc.w	.r_AtCtv-.LSP_JmpTable
			dc.w	.r_Brp-.LSP_JmpTable
			dc.w	.r_AtvpDtv-.LSP_JmpTable
			dc.w	.r_ArBpCr-.LSP_JmpTable
			dc.w	.r_AtvBtpCtDtv-.LSP_JmpTable
			dc.w	.r_AtvCv-.LSP_JmpTable
			dc.w	.r_AtvpBtvDtv-.LSP_JmpTable
			dc.w	.r_AtvDtv-.LSP_JmpTable
			dc.w	.r_ArBpDr-.LSP_JmpTable
			dc.w	.r_AtpBtvCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtDtv-.LSP_JmpTable
			dc.w	.r_AtvBvCtDtv-.LSP_JmpTable
			dc.w	.r_ArBrCpDr-.LSP_JmpTable
			dc.w	.r_AtvpBtpDtv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtDt-.LSP_JmpTable
			dc.w	.r_AtvpBvCtpDtv-.LSP_JmpTable
			dc.w	.r_BrDr-.LSP_JmpTable
			dc.w	.r_Btvp-.LSP_JmpTable
			dc.w	.r_AtvBtvDt-.LSP_JmpTable
			dc.w	.r_AtvBtpCvDt-.LSP_JmpTable
			dc.w	.r_AtvBtCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvBvCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtCtpDtv-.LSP_JmpTable
			dc.w	.r_BrCrDr-.LSP_JmpTable
			dc.w	.r_AtvCvDt-.LSP_JmpTable
			dc.w	.r_AtvCtpDtvp-.LSP_JmpTable
			dc.w	.r_ArBvCrDv-.LSP_JmpTable
			dc.w	.r_AtvCtDtv-.LSP_JmpTable
			dc.w	.r_ArBv-.LSP_JmpTable
			dc.w	.r_AtvCtvpDtv-.LSP_JmpTable
			dc.w	.r_ArBvCr-.LSP_JmpTable
			dc.w	.r_ArBvDr-.LSP_JmpTable
			dc.w	.r_AtvCtvDtv-.LSP_JmpTable
			dc.w	.r_ArBrCrpDr-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtDtv-.LSP_JmpTable
			dc.w	.r_ArBrpCrpDr-.LSP_JmpTable
			dc.w	.r_BvCv-.LSP_JmpTable
			dc.w	.r_AtvBtvCvDt-.LSP_JmpTable
			dc.w	.r_AtvDt-.LSP_JmpTable
			dc.w	.r_BtvCtpDtv-.LSP_JmpTable
			dc.w	.r_ArBr-.LSP_JmpTable
			dc.w	.r_AtvBtvCtvpDt-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtpDtp-.LSP_JmpTable
			dc.w	.r_AtvCtDt-.LSP_JmpTable
			dc.w	.r_AtvpBtpDtp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtvp-.LSP_JmpTable
			dc.w	.r_AtvBtCtDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCvDt-.LSP_JmpTable
			dc.w	.r_ArCr-.LSP_JmpTable
			dc.w	.r_AtvBtvCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBvCvDv-.LSP_JmpTable
			dc.w	.r_AtvBtvCtDt-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtpDt-.LSP_JmpTable
			dc.w	.r_BrCr-.LSP_JmpTable
			dc.w	.r_BtvCtp-.LSP_JmpTable
			dc.w	.r_AtvBtvCtDtv-.LSP_JmpTable
			dc.w	.r_BtpDtp-.LSP_JmpTable
			dc.w	.r_ArBrCp-.LSP_JmpTable
			dc.w	.r_AtBt-.LSP_JmpTable
			dc.w	.r_ArBrCrpDv-.LSP_JmpTable
			dc.w	.r_AtBtCtvp-.LSP_JmpTable
			dc.w	.r_ArBrDv-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCv-.LSP_JmpTable
			dc.w	.r_AtCt-.LSP_JmpTable
			dc.w	.r_BrpCrDr-.LSP_JmpTable
			dc.w	.r_BtvpCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvpCt-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_ArCpDr-.LSP_JmpTable
			dc.w	.r_ArBp-.LSP_JmpTable
			dc.w	.r_AtvCtp-.LSP_JmpTable
			dc.w	.r_AtvBtpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvBtDt-.LSP_JmpTable
			dc.w	.r_At-.LSP_JmpTable
			dc.w	.r_AtvpCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpCtpDv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtDtvp-.LSP_JmpTable
			dc.w	.r_AtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtpCtpDtp-.LSP_JmpTable
			dc.w	.r_BvCtpDv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtvpDt-.LSP_JmpTable
			dc.w	.r_AtvpCtpDt-.LSP_JmpTable
			dc.w	.r_BtpDv-.LSP_JmpTable
			dc.w	.r_AtvBtpCtp-.LSP_JmpTable
			dc.w	.r_AtvpBtCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvpCtDtv-.LSP_JmpTable
			dc.w	.r_ArBpCrDr-.LSP_JmpTable
			dc.w	.r_BtvDtv-.LSP_JmpTable
			dc.w	.r_AtpBtvCtvDtv-.LSP_JmpTable
			dc.w	.r_BtvCvDt-.LSP_JmpTable
			dc.w	.r_AtvBtpCtpDt-.LSP_JmpTable
			dc.w	.r_AtvCtpDtp-.LSP_JmpTable
			dc.w	.r_AtvCvDv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtDt-.LSP_JmpTable
			dc.w	.r_AtvBtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtpDt-.LSP_JmpTable
			dc.w	.r_AtBv-.LSP_JmpTable
			dc.w	.r_AtvBtpDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtp-.LSP_JmpTable
			dc.w	.r_AtvBtvpDt-.LSP_JmpTable
			dc.w	.r_AtCtpDt-.LSP_JmpTable
			dc.w	.r_AtpCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvBtpCvDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtpDt-.LSP_JmpTable
			dc.w	.r_AtvBvDtv-.LSP_JmpTable
			dc.w	.r_AtvpBvDtv-.LSP_JmpTable
			dc.w	.r_Bt-.LSP_JmpTable
			dc.w	.r_AtvpBtCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvCtDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvCtvDtvp-.LSP_JmpTable
			dc.w	.r_AtvCvDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvCtpDt-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvDtvp-.LSP_JmpTable
			dc.w	.r_AtBtvpCtpDtv-.LSP_JmpTable
			dc.w	.r_AtvBtvpCvDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBtpCtpDt-.LSP_JmpTable
			dc.w	.r_AtvBtCtvpDt-.LSP_JmpTable
			dc.w	.r_BtvCtDt-.LSP_JmpTable
			dc.w	.r_AtvpCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvpBtvpCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtBtCtp-.LSP_JmpTable
			dc.w	.r_AtBtCtpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtpDv-.LSP_JmpTable
			dc.w	.r_AtvBvDv-.LSP_JmpTable
			dc.w	.r_AtvCtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtvpCvDv-.LSP_JmpTable
			dc.w	.r_AtvBtCtDt-.LSP_JmpTable
			dc.w	.r_AtvBt-.LSP_JmpTable
			dc.w	.r_AtvBtCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvBtCtvDtv-.LSP_JmpTable
			dc.w	.r_AtvBtCtpDtp-.LSP_JmpTable
			dc.w	.r_AtvBvCtvpDtvp-.LSP_JmpTable
			dc.w	.r_AtvpBvpCvpDvp-.LSP_JmpTable
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	$0000		; dummy code
			dc.w	-1		; extended code
			dc.w	.r_rewind-.LSP_JmpTable
			dc.w	$0000		; SetBpm code (not used in this music)
			dc.w	$0000		; no GetPos (not supported in insane player)

; 257 specific callback
.r_None:
		move.l	a0,(a1)+
		rts

.r_Bp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_Bv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_ArBrCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_BvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_Cp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_ArCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Ar:
		move.l	a0,(a1)+
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	4(a4),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	8(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_Br:
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtvpBtpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBvCrDr:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvBtpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Cr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		rts

.r_Dv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		rts

.r_BpCp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.l	a0,(a1)
		rts

.r_Cv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		rts

.r_Ctp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Atv:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArDr:
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_Btp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Atvp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_Btv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrCr:
		move.l	a0,(a1)+
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_CpDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	a0,(a1)
		rts

.r_AtCtv:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_Brp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_AtvpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_ArBpCr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_ArBpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtpBtvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrCpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	4(a4),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	8(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvpBtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrDr:
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_Btvp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCrDr:
		move.l	a0,(a1)+
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_AtvCvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBvCrDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvCtvpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBvCr:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_ArBvDr:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrCrpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrpCrpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BvCv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		rts

.r_AtvBtvCvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_BtvCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBr:
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvBtvCtvpDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtpDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_ArCr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvBtvCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCtDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtpDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BrCr:
		move.l	a0,(a1)+
		move.l	.resetv+4(pc),a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		rts

.r_BtvCtp:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$06,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtpDtp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBrCp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtBt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrCrpDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtBtCtvp:
		move.b	(a0)+,$29(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArBrDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	.resetv+8(pc),a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		rts

.r_AtvpBtvpCv:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtCt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BrpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$10(a6)
		move.w	(a3)+,$14(a6)
		move.l	a0,(a1)
		rts

.r_BtvpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_ArCpDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.l	.resetv+0(pc),a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_ArBp:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.l	.resetv+12(pc),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_AtvCtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_At:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpCtpDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtpDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BvCtpDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$04,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtpCtvpDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCtpDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_BtpDv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtpCtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCtDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_ArBpCrDr:
		move.l	a0,(a1)+
		addq.w	#4,a1
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		move.l	(a4)+,a3
		move.l	(a3)+,$30(a6)
		move.w	(a3)+,$34(a6)
		move.l	(a4)+,a3
		move.l	(a3)+,$20(a6)
		move.w	(a3)+,$24(a6)
		move.l	4(a4),a3
		move.l	(a3)+,(a6)
		move.w	(a3)+,$04(a6)
		move.l	a0,(a1)
		rts

.r_BtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtpBtvCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvCvDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0a,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCtpDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtpDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvCvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtpDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtBv:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtp:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtCtpDt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtpCvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtpDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_Bt:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$02,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$09,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvCtpDt:
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtBtvpCtpDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCvDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0b,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,4(a4)
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,8(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtpCtpDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtvpDt:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_BtvCtDt:
		move.b	(a0)+,$19(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0e,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvpCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBtvpCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtBtCtp:
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtBtCtpDtvp:
		move.b	(a0)+,$39(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtpDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$07,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvCtvp:
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$05,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$26(a6)
		lea		.resetv+4(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvBtvpCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtvpCvDv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$16(a6)
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtDt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBt:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$03,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv+8(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtvDtv:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBtCtpDtp:
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0f,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$10(a6)
		move.w	(a2)+,$14(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

.r_AtvBvCtvpDtvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$0d,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		lea		.resetv(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,$30(a6)
		move.w	(a2)+,$34(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,$20(a6)
		move.w	(a2)+,$24(a6)
		move.l	a2,(a4)+
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,4(a4)
		move.l	a0,(a1)
		rts

.r_AtvpBvpCvpDvp:
		move.b	(a0)+,$39(a6)
		move.b	(a0)+,$29(a6)
		move.b	(a0)+,$19(a6)
		move.b	(a0)+,$09(a6)
		move.l	a0,(a1)+
		move.l	(a1)+,a0
		moveq	#$01,d0
		move.w	d0,$96-$a0(a6)
		move.b	d0,(a0)
		move.l	(a1),a0
		move.w	(a0)+,$36(a6)
		move.w	(a0)+,$26(a6)
		move.w	(a0)+,$16(a6)
		move.w	(a0)+,$06(a6)
		lea		.resetv+12(pc),a4
		movea.l	a1,a2
		add.w	(a0)+,a2
		move.l	(a2)+,(a6)
		move.w	(a2)+,$04(a6)
		move.l	a2,(a4)+
		move.l	a0,(a1)
		rts

